# Site settings
title: Cingnan Blog
SEOTitle: 周幸楠的博客 | Cingnan Blog
header-img: img/home-bg-art.jpg
email: zhouxingnan2016@gmail.com
description: "关于程序 | 周幸楠，Traffic Engineer| 这里是 @Cingnan 周某人不会倒闭的个人博客。"
keyword: "周幸楠, Cingnan, Cingnan,  @huxpro, 周幸楠的博客, Cingnan Blog, 博客, 个人网站, Python"
url: "https://www.zhouxingnan.com/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

google_analytics: 'UA-159388298-1'


# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     1836954672
youtube_username:  channel/UC6GsCmpXiaRbhB3E6Y1lIuQ
googlescholar_username: zEmmDhgAAAAJ
#zhihu_username:     周星星
github_username:    luckysouthchou
twitter_username:   ChouLuckysouth
facebook_username:  100011798162179
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: luckysouthchou

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "如果害怕这个世界的更新速度<br>那就用自己苟延残喘的学习能力去挖掘"
sidebar-avatar: /img/datou-lucky.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
            {
                    title: "faith",
                    href: "https://faithio.cn/"
                }
]
gems: [jekyll-paginate]
